# .travis.yml

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - '9.3'
      before_install:
        - cd mobile && yarn
      script:
        - yarn test
      cache:
        directories:
        - ./mobile/node_modules
    - stage: deploy gh-pages
      if: branch = master
      sudo: required
      language: node_js
      services:
        - docker
      node_js:
        - '8'
      only:
        - master
      cache:
        yarn: true
      before_install:
        - docker pull lucascst/gh-pages-docker-travis
      script:
        - echo "GH_NAME=${GH_NAME}" >> docs/.env
        - echo "GH_EMAIL=${GH_EMAIL}" >> docs/.env
        - echo "GH_TOKEN=${GH_TOKEN}" >> docs/.env
        - docker run -v `pwd`:"/app" -w "/app" --env-file docs/.env lucascst/gh-pages-docker-travis bash -c "cd docs; sh publish.sh"