export default {
  item: {
    backgroundColor: 'white',
    paddingTop: 20,
  },
  details_main: {
    flex: 1,
    flexDirection: 'column',
    margin: 0,
    padding: 0,
    width: '100%',
    backgroundColor: '#171717',
  },
  info: {
    backgroundColor: 'white',
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: '30%',
  },
  description: {
    backgroundColor: 'white',
    paddingTop: 0,
    paddingBottom: 10,
  },
  image: {
    height: 210,
    width: '100%',
  },
  gradient: {
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  order_main: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#08623F',
    borderBottomColor: '#171717',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,

  },
  items: {
    backgroundColor: '#171717',
    flexGrow: 1,
    paddingVertical: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 0,
  },
  order_item: {
    backgroundColor: '#08623F',
    flexGrow: 1,
    paddingVertical: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 0,
  },
  order_title: {
    color: 'white',
    fontSize: 25,
  },
  order_subtitle: {
    color: 'white',
    fontSize: 20,
  },
  order_body: {
    color: 'white',
    fontSize: 16,
  },
  order_price: {
    color: 'white',
    fontSize: 25,
  },
  imageItems: {
    flexGrow: 3,
    resizeMode: 'cover',
    width: null,
    height: 150,
  },
  text: {
    fontWeight: 'normal',
    color: 'black',
    fontSize: 20,
    textShadowOffset: {
      width: 0,
      height: 0,
   },
    textShadowColor: '#5A5A5A',
    textShadowRadius: 5,
    alignSelf: 'center',
    marginLeft: 0,
    backgroundColor: 'transparent',
  },
  textVendor: {
    fontWeight: 'normal',
    color: 'black',
    fontSize: 10,
    alignSelf: 'flex-start',
  },
  textInfo: {
    fontWeight: 'normal',
    color: 'black',
    fontSize: 30,
  },
  textDescription: {
    fontWeight: 'normal',
    color: '#c2c2d6',
    fontSize: 15,
  },
  customBtnBG: {
    backgroundColor: "#0EAC6F",
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  buttonCard:{
    backgroundColor: 'transparent',
    paddingTop: 5,
    paddingBottom: 10,
    paddingLeft: '70%',
  },
  customBtnText: {
    fontSize: 20,
    fontWeight: '400',
    color: 'white',
    alignItems: 'flex-start',
  },
  PickerStyle: {
    position: 'absolute',
    top: 215,
    left: '70%',
    paddingVertical: 50,
    paddingHorizontal: 50,
    color: 'black',
    alignSelf: 'center',
   },
   PickerText: {
    position: 'absolute',
    paddingTop: 230,
    left: '70%',
    color: 'black',
    alignSelf: 'center',
    fontSize: 15,
   },
   order_main: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#08623F',
    borderBottomColor: '#171717',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
   },
   order_item: {
    backgroundColor: '#08623F',
    flexGrow: 1,
    paddingVertical: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 0,
   },
   order_title: {
    color: 'white',
    fontSize: 25,
   },
   order_subtitle: {
    color: 'white',
    fontSize: 20,
   },
   order_body: {
    color: 'white',
    fontSize: 16,
   },
   order_price: {
    color: 'white',
    fontSize: 25,
   },
   details_main: {
    flex: 1,
    flexDirection: 'column',
    margin: 0,
    padding: 0,
    width: '100%',
    backgroundColor: '#171717',
    },
};
