export default {
  item: {
    backgroundColor: 'transparent',
    paddingTop: 160,
  },
  info: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 0,
  },
  description: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 10,
  },
  image: {
    height: 210,
    width: '100%',
  },
  gradient: {
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  text: {
    fontWeight: 'normal',
    color: 'white',
    fontSize: 25,
    textShadowOffset: {
      width: 2,
      height: 2,
    },
    textShadowColor: '#5A5A5A',
    textShadowRadius: 5,
    alignSelf: 'center',
    marginLeft: 0,
    backgroundColor: 'transparent',
  },
  textVendor: {
    fontWeight: 'normal',
    color: 'white',
    fontSize: 20,
  },
  textInfo: {
    fontWeight: 'normal',
    color: 'white',
    fontSize: 30,
  },
  textDescription: {
    fontWeight: 'normal',
    color: '#c2c2d6',
    fontSize: 20,
  },
    customBtnBG: {
     position: 'absolute',
     backgroundColor: "#0EAC6F",
     top: '85%',
     left: '70%',
     paddingVertical: 10,
     paddingHorizontal: 15,
   },
    customBtnText: {
      fontSize: 20,
      fontWeight: '400',
      color: 'white',
      alignItems: 'flex-start',
    },
    PickerStyle: {
     position: 'absolute',
     top: '40%',
     left: '70%',
     paddingVertical: 50,
     paddingHorizontal: 50,
     color: 'white',
     alignSelf: 'center',
   },
   PickerText: {
     position: 'absolute',
     top: '40%',
     left: '70%',
     color: 'white',
     alignSelf: 'center',
   },
     order_main: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#08623F',
    borderBottomColor: '#171717',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
   },
     order_item: {
    backgroundColor: '#08623F',
    flexGrow: 1,
    paddingVertical: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 0,
    },
    order_title: {
      color: 'white',
      fontSize: 25,
    },
    order_subtitle: {
      color: 'white',
      fontSize: 18,
    },
    order_price: {
      color: 'white',
      fontSize: 25,
    }
};
